# Scikit-learn - Topic 2 - Split your data, fit a model, predict and save the model.

## <img width="3%" height="3%" align="top"  src="https://codeinstitute.s3.amazonaws.com/predictive_analytics/jupyter_notebook_icons/Icon%202%20-%20Unit%20Objective.png"> Topic Objectives

* Learn and implement the basic workflow for splitting the data, fitting a model, predicting on data and saving the model.

---

## <img width="3%" height="3%" align="top"  src="https://codeinstitute.s3.amazonaws.com/predictive_analytics/jupyter_notebook_icons/Icon%204%20-%20Import%20Package%20for%20Learning.png"> Import Packages for Learning

We will install scikit-learn, xgboost, feature-engine and yellow brick to run our exercises.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style("whitegrid")

---

## <img width="3%" height="3%" align="top"  src="https://codeinstitute.s3.amazonaws.com/predictive_analytics/jupyter_notebook_icons/Icon%2010-%20Lesson%20Content.png"> Scikit-learn - Topic 02 - Split your data, fit a model and predict

In this unit, we will cover how to:
  * Split your data
  * Fit a model
  * Run predictions with the fitted model
  * Save the model so that you can use it later

<img width="3%" height="3%" align="top"  src="https://codeinstitute.s3.amazonaws.com/predictive_analytics/jupyter_notebook_icons/Icon%207-%20Note.png"> You are interested in splitting your data in supervised learning. In conventional ML, like in Scikit-learn, we split the data into Train and Test sets.
* The validation set is part of the Train set. When using a specific Scikit-learn function for hyperparameter optimisation, the validation set is grabbed automatically. Therefore, we will split it into Train and Test sets only.
* If you want a refresher on Train, Validation, and Test sets, refer to the Apply model evaluation metrics and analyse model performance lesson.

Let's consider the iris dataset. It contains records of three classes of iris plants, with measurements of petals and sepals.

In [2]:
df = sns.load_dataset('iris')
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

<img width="3%" height="3%" align="top"  src="https://codeinstitute.s3.amazonaws.com/predictive_analytics/jupyter_notebook_icons/Icon%207-%20Note.png"> How do you know which variables are features and which variable is a target variable?
* It will depend on the context of your ML project. You will need to know or investigate the objective of your ML project to determine the features and the target.


<img width="3%" height="3%" align="top"  src="https://codeinstitute.s3.amazonaws.com/predictive_analytics/jupyter_notebook_icons/Icon%207-%20Note.png"> For this notebook, species is our chosen target variable. There are three species. We need to classify the species according to the flower's petal and sepal. Our ML task will then be classification.

In [3]:
df['species'].value_counts()

setosa        50
versicolor    50
virginica     50
Name: species, dtype: int64

---

### <img width="3%" height="3%" align="top"  src="https://codeinstitute.s3.amazonaws.com/predictive_analytics/jupyter_notebook_icons/Icon%2010-%20Lesson%20Content.png"> Split your data

We use `train_test_split()` to split the data. The documentation is [here](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html). The parameters we will use are:
* The first two are the features and target, respectively. In this case, for the features, you drop species, and for the target, you subset species.
* ``test_size:`` it represents the data proportion to include in the test set. We set it at 0.2
* ``random_state:``According to the documentation, it controls the shuffling applied to the data before applying the split. Pass an int for reproducible output across multiple function calls. It can be any positive integer. We suggest keeping the same random_state value across your project. We will select here 101

<img width="3%" height="3%" align="top"  src="https://codeinstitute.s3.amazonaws.com/predictive_analytics/jupyter_notebook_icons/Icon%206%20-%20Warning.png"> `random_state` is a critical parameter in ML, which we will use in other use cases. It essentially gives **REPRODUCIBILITY** to your project. That means the same result you get here right now; another person will get elsewhere at another time.

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop(['species'],axis=1),
                                                    df['species'],
                                                    test_size=0.2,
                                                    random_state=101)

print("* Train set:", X_train.shape, y_train.shape, "\n* Test set:",  X_test.shape, y_test.shape)

* Train set: (120, 4) (120,)
* Test set: (30, 4) (30,)

Let's have a look at `X_train`
* Those will be the features used to train the model
* Note the features are numbers. Scikit-learn uses numbers to fit models. That is why we have to encode categorical data
* In this dataset, we don't need any data cleaning or categorical encoding.

In [5]:
X_train.head()

     sepal_length  sepal_width  petal_length  petal_width
104           6.5          3.0           5.8          2.2
89            5.5          2.5           4.0          1.3
116           6.5          3.0           5.5          1.8
82            5.8          2.7           3.9          1.2
112           6.8          3.0           5.5          2.1

Let's inspect `y_train`. These are categories.
* When the ML task is classification, Scikit-learn handles either numbers or categories for the target variable.

In [6]:
y_train

104     virginica
89     versicolor
116     virginica
82     versicolor
112     virginica
          ...
63     versicolor
70     versicolor
81     versicolor
11         setosa
95     versicolor
Name: species, Length: 120, dtype: object

In addition, `y_train` is a Pandas Series.

In [ ]:
type(y_train)

---

### <img width="3%" height="3%" align="top"  src="https://codeinstitute.s3.amazonaws.com/predictive_analytics/jupyter_notebook_icons/Icon%2010-%20Lesson%20Content.png"> Fit your model

You got a preview of tree-based algorithms in the Algorithms topic. Even though we have a dedicated unit for tree-based algorithms, here we will use a decision tree algorithm to fit a model to demonstrate the basic workflow for fitting a model.
* We will use `DecisionTreeClassifier()`, the documentation is [here](https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html)
* We create a python object/variable called model and instantiate `DecisionTreeClassifier()`. A common convention is to set the object name as a model.


<img width="3%" height="3%" align="top"  src="https://codeinstitute.s3.amazonaws.com/predictive_analytics/jupyter_notebook_icons/Icon%206%20-%20Warning.png">  Note: we created a model and fit. We can do that since the data doesn't require a pre-processing step, like data cleaning or categorical encoding, for the fitting.

* Fitting the model on its own is fine as a learning experience. However, in our later exercises, we will not fit the model but instead use a pipeline that contains a series of steps, where typically, the last step will be the model.

In [7]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()

Next, we fit the model with the train set - features (`X_train`) and target (`y_train`)
* We use `.fit()` method and parse `X_train` and `y_train`. Simple as that.

In [9]:
model.fit(X_train,y_train)

DecisionTreeClassifier()

---

### <img width="3%" height="3%" align="top"  src="https://codeinstitute.s3.amazonaws.com/predictive_analytics/jupyter_notebook_icons/Icon%2010-%20Lesson%20Content.png"> Run predictions

Let's predict the test set using our model.
* We use `.predict()` and parse the test set features (`X_test`)
* The answer is an array

In [10]:
model.predict(X_test)

array(['setosa', 'setosa', 'setosa', 'versicolor', 'versicolor',
       'virginica', 'versicolor', 'versicolor', 'virginica', 'setosa',
       'virginica', 'setosa', 'setosa', 'virginica', 'virginica',
       'versicolor', 'versicolor', 'versicolor', 'setosa', 'virginica',
       'versicolor', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'virginica', 'setosa', 'setosa'],
      dtype=object)

You can predict the probability (between 0.0 and 1.0) for each class for a given observation using `.predict_proba()`

In [11]:
model.predict_proba(X_test)

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.]])

Ideally, we should predict on the Train and Test set, set a performance metric and evaluate model performance.
* We will not evaluate the model yet. We will leave it until another unit
* The idea here is to feel how it works 'under the hood' when doing a basic training and predicting process.

Let's assume now you want to predict on real-time data.
* In an application, you will likely create an interface to collect the data or will get the data from somewhere else, from an API, for example.
* In this case, we will manually create a DataFrame that contains the features. We call that X_live. It will have one row only (you could have a set of rows, that would mean running predictions in a batch; in our case, it is only one prediction)


<img width="3%" height="3%" align="top"  src="https://codeinstitute.s3.amazonaws.com/predictive_analytics/jupyter_notebook_icons/Icon%207-%20Note.png"> In theory, you can set any value to the variable, But in practice, the values will follow the actual data distribution.

In [12]:
X_live = pd.DataFrame(data={'sepal_length':6.0,
                            'sepal_width':3.9,
                            'petal_length':2.5,
                            'petal_width':0.9},
                      index=[0] # the DataFrame needs an index (either number or category), we just parsed the number 0
                      )
X_live

   sepal_length  sepal_width  petal_length  petal_width
0           6.0          3.9           2.5          0.9

Let's predict using this live data.

In [13]:
model.predict(X_live)

array(['versicolor'], dtype=object)

The model is 100% confident it is a determined class.

In [14]:
model.predict_proba(X_live)

array([[0., 1., 0.]])

We saw already this class is Versicolor, but you cross-check the labels orders with `.unique()`

In [15]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

### <img width="3%" height="3%" align="top"  src="https://codeinstitute.s3.amazonaws.com/predictive_analytics/jupyter_notebook_icons/Icon%2010-%20Lesson%20Content.png"> Save your model

We can save either an ML model or an ML pipeline as a .pkl file with a library called joblib.
* You need the function `joblib.dump()`, the documentation is [here](https://joblib.readthedocs.io/en/latest/generated/joblib.dump.html). We will parse the `value` of the arguments as the file we want to save and the `filename` as the directory + filename + .pkl (we are saving at the root level).

In [16]:
import joblib
joblib.dump(value=model , filename="my_first_ml_model.pkl")

['my_first_ml_model.pkl']

Once you are in an application or another notebook, you can load with `joblib.load()`. The documentation is [here](https://joblib.readthedocs.io/en/latest/generated/joblib.load.html). You will parse the argument `filename` as the directory + filename + .pkl

In [17]:
loaded_model = joblib.load(filename="my_first_ml_model.pkl")
loaded_model

DecisionTreeClassifier()

---

<img width="3%" height="3%" align="top"  src="https://codeinstitute.s3.amazonaws.com/predictive_analytics/jupyter_notebook_icons/Icon%209-%20Well%20done.png"> Awesome!! 

<img width="3%" height="3%" align="top"  src="https://codeinstitute.s3.amazonaws.com/predictive_analytics/jupyter_notebook_icons/Icon%207-%20Note.png"> Does that mean I am ready to create an ML model for the world and solve big challenges?
* Almost. We've started the ML journey now! 
* We still need to cover more topics. Now, let's have some fun!

---